---
name: Function Main workflow
# PR closed trigger
on:
  # Trigger the workflow on pull request
  push:
    branches:
      - master
    paths-ignore:
      - 'iac/**'
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo and Init terraform
        uses: actions/checkout@v2.0.0
