---
name: Terraform Plan Workflow
# PR closed trigger
on:
  # Trigger the workflow on pull request
  pull_request:
    branches:
      - master
    paths:
      - "iac/**"
jobs:
  plan_terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo and Init terraform
        uses: actions/checkout@v2.0.0
      - name: Select TF var (last commit file in tfvars/ folder)
        run: |
          export LAST_VAR_FILE="tfvars/$(ls tfvars/ -1t|head -1)"
          echo ::set-env name=lastfile::${LAST_VAR_FILE}
        working-directory: ./
      - name: Build Path 
        run: |
          export BUSINESS_UNIT=$(grep "business_unit \+=" ${{ env.lastfile }} | awk -F\" '{print tolower($2)}')
          export DEPARTMENT=$(grep "department \+=" ${{ env.lastfile }} | awk -F\" '{print tolower($2)}')
          export PROJECT=$(grep "project \+=" ${{ env.lastfile }} | awk -F\" '{print tolower($2)}')
          if [[ -z $BUSINESS_UNIT || -z $DEPARTMENT || -z $PROJECT ]]; then echo "Wrong tfvars content" && exit 1;fi
          export ARTIFACTORY_SUBPATH="${BUSINESS_UNIT}/${DEPARTMENT}/${PROJECT}"
          echo ::set-env name=artifactorysubpath::${ARTIFACTORY_SUBPATH}
        working-directory: ./
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@v0.7.1
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          args: '-backend-config="username=${{ secrets.ARTIFACTORY_USER }}" -backend-config="password=${{ secrets.ARTIFACTORY_PASSWORD }}" -backend-config="url=${{ secrets.ARTIFACTORY_URL }}" -backend-config="repo=${{ secrets.ARTIFACTORY_REPO }}" -backend-config="subpath=${{ env.artifactorysubpath }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Select TF var (last commit file in tfvars/ folder)
        run: |
          export LAST_VAR_FILE="tfvars/$(ls tfvars/ -1t|head -1)"
          echo ::set-env name=lastfile::$LAST_VAR_FILE
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@v0.7.1
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          args: '-var-file=${{ env.lastfile }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
