---
name: Terraform Validate Workflow

on:
  # Trigger the workflow on dev push
  push:
    # Future: Run in ALL branches
    branches:
      - dev
    paths:
      - "iac/**"
env:
  PROJECT_TFVARS: project.tfvars
jobs:
  validate_terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo and Init terraform
        uses: actions/checkout@v2.0.0
      - name: Select TF var (last commit file in tfvars/ folder)
        run: |
          export TERRAFORM_ARG_TFVARS=""
          for tfvarfile in *.tfvars; do TERRAFORM_ARG_TFVARS="-var-file=$tfvarfile $TERRAFORM_ARG_TFVARS"; done
          echo ::set-env name=terraformargtfvars::${TERRAFORM_ARG_TFVARS}
        working-directory: ./iac
      - name: Build Path 
        run: |
          export BUSINESS_UNIT=$(grep "business_unit \+=" ${{ env.PROJECT_TFVARS }} | awk -F\" '{print tolower($2)}')
          export DEPARTMENT=$(grep "department \+=" ${{ env.PROJECT_TFVARS }} | awk -F\" '{print tolower($2)}')
          export PROJECT=$(grep "project \+=" ${{ env.PROJECT_TFVARS }} | awk -F\" '{print tolower($2)}')
          if [[ -z $BUSINESS_UNIT || -z $DEPARTMENT || -z $PROJECT ]]; then echo "Wrong project.tfvars content" && exit 1;fi
          export TFSTATE_PATH="${BUSINESS_UNIT}/${DEPARTMENT}/${PROJECT}"
          echo ::set-env name=tfstatepath::${TFSTATE_PATH}
          env
        working-directory: ./iac
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@v0.7.1
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@v0.7.1
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
